'use client';

import React, { useEffect, useState } from 'react';
import { Mic, ArrowLeft, Award, Sparkles, HelpCircle, BookOpen, Calendar, ChevronRight, Play, Loader2 } from 'lucide-react';
import { PageHeader } from '@/components/dashboard/page-header';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Accordion, AccordionItem } from '@/components/ui/accordion';
import { LoadingSpinner } from '@/components/ui/loading-spinner';
import { startInterview, getMySessions, getSession, submitAnswers } from '@/lib/api/interview.api';
import { useToast } from '@/components/ui/Toast';
import { InterviewSession, InterviewQuestion } from '@/types';
import { motion, AnimatePresence } from 'framer-motion';
import dynamic from 'next/dynamic';

const ScoreRing = dynamic(() => import('@/components/ui/ScoreRing').then(mod => mod.ScoreRing), {
  ssr: false,
});

type LocalView = 'list' | 'start' | 'in-progress' | 'results';

export default function InterviewsPage() {
  const { addToast } = useToast();
  const [currentView, setCurrentView] = useState<LocalView>('list');
  const [sessions, setSessions] = useState<InterviewSession[]>([]);
  const [isLoadingHistory, setIsLoadingHistory] = useState(true);

  // Active Session Details
  const [activeSession, setActiveSession] = useState<InterviewSession | null>(null);
  const [currentQuestionIdx, setCurrentQuestionIdx] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string>>({}); // { questionId: answerText }

  // Form Inputs
  const [targetRole, setTargetRole] = useState('');
  const [focusTopic, setFocusTopic] = useState('');
  const [isCreating, setIsCreating] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const loadHistory = async () => {
    setIsLoadingHistory(true);
    try {
      const response = await getMySessions();
      if (response.success && response.data) {
        setSessions(response.data);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setIsLoadingHistory(false);
    }
  };

  useEffect(() => {
    if (currentView === 'list') {
      loadHistory();
    }
  }, [currentView]);

  const handleStartSession = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!targetRole.trim() || !focusTopic.trim()) return;

    setIsCreating(true);
    try {
      const response = await startInterview(targetRole, focusTopic);
      if (response.success && response.data) {
        setActiveSession(response.data);
        setAnswers({});
        setCurrentQuestionIdx(0);
        setCurrentView('in-progress');
        addToast('Mock interview session generated by AI!', 'success');
      } else {
        addToast(response.message || 'Failed to start interview', 'error');
      }
    } catch (err: any) {
      console.error(err);
      addToast('Failed to create mock interview questions.', 'error');
    } finally {
      setIsCreating(false);
    }
  };

  const handleAnswerChange = (text: string) => {
    if (!activeSession) return;
    const questions = activeSession.questions;
    const currentQuestion = questions[currentQuestionIdx];
    setAnswers((prev) => ({ ...prev, [currentQuestion.id]: text }));
  };

  const handleNext = () => {
    if (!activeSession) return;
    if (currentQuestionIdx < activeSession.questions.length - 1) {
      setCurrentQuestionIdx((prev) => prev + 1);
    }
  };

  const handlePrev = () => {
    if (currentQuestionIdx > 0) {
      setCurrentQuestionIdx((prev) => prev - 1);
    }
  };

  const handleSubmitInterview = async () => {
    if (!activeSession) return;
    setIsSubmitting(true);

    const payload = Object.entries(answers).map(([questionId, answerText]) => ({
      questionId,
      answerText,
    }));

    try {
      const response = await submitAnswers(activeSession.id, payload);
      if (response.success && response.data) {
        setActiveSession(response.data);
        setCurrentView('results');
        addToast('Interview graded! ATS results generated.', 'success');
      } else {
        addToast(response.message || 'Failed to submit responses', 'error');
      }
    } catch (err) {
      addToast('Grading error. Try submitting again.', 'error');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleViewResults = async (session: InterviewSession) => {
    try {
      const res = await getSession(session.id);
      if (res.success && res.data) {
        setActiveSession(res.data);
        setCurrentView('results');
      }
    } catch (err) {
      addToast('Could not load session transcript.', 'error');
    }
  };

  const allQuestionsAnswered = () => {
    if (!activeSession) return false;
    return activeSession.questions.every((q) => answers[q.id]?.trim().length > 0);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="space-y-8"
    >
      {/* 1. LIST VIEW */}
      {currentView === 'list' && (
        <div className="space-y-8 animate-fadeIn">
          <PageHeader
            title="Mock Interviews"
            subtitle="Practice interactive technical and behavioral interview sessions."
          />

          {/* Start New Session CTA */}
          <Card className="border border-[#3C3489]/20 hover:shadow-md transition-shadow">
            <CardContent className="p-6 flex flex-col md:flex-row items-center justify-between gap-6">
              <div className="flex items-center gap-4">
                <div className="p-3 bg-[#3C3489]/5 rounded-xl text-[#3C3489]">
                  <Mic className="w-8 h-8" />
                </div>
                <div>
                  <h3 className="font-bold text-lg text-[#1A1832]">Start New Interview</h3>
                  <p className="text-xs text-[#6B6A8A]">Practice with AI-generated questions tailored to your goals</p>
                </div>
              </div>
              <Button
                onClick={() => setCurrentView('start')}
                className="bg-[#3C3489] hover:bg-[#534AB7] text-white font-bold"
              >
                Start Interview →
              </Button>
            </CardContent>
          </Card>

          {/* Past Sessions List */}
          <div className="space-y-4">
            <h3 className="font-bold text-[#1A1832] text-lg">Past Sessions</h3>
            
            {isLoadingHistory ? (
              <LoadingSpinner size="md" />
            ) : sessions.length > 0 ? (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {sessions.map((item) => (
                  <Card key={item.id} className="hover:shadow-md transition-shadow">
                    <CardHeader className="pb-2">
                      <CardTitle className="truncate">{item.role}</CardTitle>
                      <CardDescription className="truncate text-xs">{item.topic}</CardDescription>
                    </CardHeader>
                    <CardContent className="pt-2 text-xs flex justify-between items-center">
                      <span className="text-[#6B6A8A]">
                        {new Date(item.createdAt).toLocaleDateString()}
                      </span>
                      {item.score !== null ? (
                        <Badge variant={item.score >= 80 ? 'success' : item.score >= 60 ? 'warning' : 'error'}>
                          {item.score}% Match
                        </Badge>
                      ) : (
                        <Badge variant="info">In Progress</Badge>
                      )}
                    </CardContent>
                    <CardFooter className="pt-4 border-t border-gray-100 flex justify-end">
                      <Button
                        onClick={() => handleViewResults(item)}
                        variant="outline"
                        size="sm"
                        className="text-xs border-[#3C3489] text-[#3C3489] hover:bg-[#F4F3FF]/40 font-bold"
                      >
                        View Results
                      </Button>
                    </CardFooter>
                  </Card>
                ))}
              </div>
            ) : (
              <p className="text-center text-xs text-[#6B6A8A] py-8">No mock interviews recorded yet.</p>
            )}
          </div>
        </div>
      )}

      {/* 2. START VIEW */}
      {currentView === 'start' && (
        <div className="max-w-xl mx-auto space-y-6 animate-fadeIn">
          <button
            onClick={() => setCurrentView('list')}
            className="flex items-center gap-2 text-xs font-bold text-[#3C3489] hover:underline"
          >
            <ArrowLeft className="w-4 h-4" /> Back to list
          </button>
          
          <Card className="shadow-md">
            <CardHeader className="text-center">
              <div className="p-4 bg-[#3C3489]/5 rounded-full w-fit mx-auto mb-4 text-[#3C3489]">
                <Mic className="w-8 h-8" />
              </div>
              <CardTitle>Prepare Mock Interview</CardTitle>
              <CardDescription>
                Specify your role and technical stack. We will generate 5 questions.
              </CardDescription>
            </CardHeader>
            <CardContent className="p-6 pt-0">
              <form onSubmit={handleStartSession} className="space-y-5">
                <Input
                  label="Role"
                  placeholder="e.g. React Developer"
                  value={targetRole}
                  onChange={(e) => setTargetRole(e.target.value)}
                  disabled={isCreating}
                  required
                />
                <Input
                  label="Topic"
                  placeholder="e.g. Hooks and State Management"
                  value={focusTopic}
                  onChange={(e) => setFocusTopic(e.target.value)}
                  disabled={isCreating}
                  required
                />
                <Button
                  type="submit"
                  variant="coral"
                  className="w-full bg-[#D85A30] hover:bg-[#D85A30]/90 text-white font-bold"
                  isLoading={isCreating}
                >
                  Start →
                </Button>
              </form>
            </CardContent>
          </Card>
        </div>
      )}

      {/* 3. IN-PROGRESS VIEW */}
      {currentView === 'in-progress' && activeSession && (
        <div className="max-w-2xl mx-auto space-y-6 animate-fadeIn relative">
          <div className="flex justify-between items-center text-xs text-[#6B6A8A]">
            <button
              onClick={() => setCurrentView('list')}
              className="flex items-center gap-1.5 font-bold text-[#3C3489] hover:underline"
            >
              <ArrowLeft className="w-4 h-4" /> Exit
            </button>
            <span className="font-bold text-[#1A1832] bg-[#F4F3FF] px-3 py-1 rounded-full border border-[#3C3489]/10">
              Question {currentQuestionIdx + 1} of 5
            </span>
          </div>

          <Card className="shadow-lg border-[#3C3489]/20">
            <CardContent className="p-8 space-y-6">
              <div className="text-center space-y-3">
                <span className="text-[10px] uppercase font-black text-[#6B6A8A] tracking-widest">
                  {activeSession.questions[currentQuestionIdx].context || 'Question Context'}
                </span>
                <h3 className="text-2xl font-semibold text-[#1A1832] leading-relaxed">
                  {activeSession.questions[currentQuestionIdx].questionText}
                </h3>
              </div>

              <div className="space-y-2">
                <label className="text-xs font-bold text-[#1A1832]">Your Answer</label>
                <textarea
                  className="w-full h-40 p-4 border border-gray-200 rounded-xl bg-white text-[#1A1832] text-sm focus:border-[#3C3489] focus:ring-1 focus:ring-[#3C3489] outline-none placeholder:text-gray-300 resize-none leading-relaxed"
                  placeholder="Type your detailed answer here…"
                  value={answers[activeSession.questions[currentQuestionIdx].id] || ''}
                  onChange={(e) => handleAnswerChange(e.target.value)}
                  disabled={isSubmitting}
                />
              </div>
            </CardContent>
            <CardFooter className="p-6 bg-gray-50/50 border-t border-gray-100 flex justify-between items-center">
              <Button
                variant="secondary"
                size="sm"
                onClick={handlePrev}
                disabled={currentQuestionIdx === 0}
              >
                ← Previous
              </Button>
              
              {currentQuestionIdx < activeSession.questions.length - 1 ? (
                <Button variant="primary" size="sm" onClick={handleNext}>
                  Next →
                </Button>
              ) : (
                <Button
                  onClick={handleSubmitInterview}
                  variant="coral"
                  className="bg-[#D85A30] hover:bg-[#D85A30]/90 text-white font-bold"
                  disabled={!allQuestionsAnswered() || isSubmitting}
                  isLoading={isSubmitting}
                >
                  Submit All Answers
                </Button>
              )}
            </CardFooter>
          </Card>

          {/* Custom grading overlay */}
          {isSubmitting && (
            <div className="absolute inset-0 bg-white/80 z-20 flex flex-col items-center justify-center text-center">
              <LoadingSpinner size="lg" className="mb-4" />
              <h3 className="font-extrabold text-[#1A1832] text-lg">AI is grading your interview…</h3>
              <p className="text-xs text-[#6B6A8A] mt-1">This will take a moment, evaluating your replies.</p>
            </div>
          )}
        </div>
      )}

      {/* 4. RESULTS VIEW */}
      {currentView === 'results' && activeSession && (
        <div className="space-y-8 animate-fadeIn">
          <div className="flex justify-between items-center border-b border-gray-100 pb-4">
            <div>
              <h2 className="text-2xl font-extrabold text-[#1A1832]">{activeSession.role} Results</h2>
              <p className="text-xs text-[#6B6A8A] mt-1">Topic: {activeSession.topic}</p>
            </div>
            <Button
              onClick={() => setCurrentView('list')}
              variant="outline"
              size="sm"
              className="border-[#3C3489] text-[#3C3489] font-bold"
            >
              Back to Interviews
            </Button>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
            {/* Score Ring Card */}
            <Card className="lg:col-span-4 flex flex-col items-center justify-center p-6 text-center">
              <CardHeader className="pb-2 text-center p-0">
                <CardTitle>Grading Evaluation</CardTitle>
                <CardDescription className="text-xs">Overall response match score</CardDescription>
              </CardHeader>
              <CardContent className="p-0 mt-6 flex flex-col items-center w-full">
                <ScoreRing score={activeSession.score || 0} size={150} />
                <p className="text-xs text-[#6B6A8A] mt-6 leading-relaxed max-w-[240px]">
                  {activeSession.overallFeedback}
                </p>
              </CardContent>
            </Card>

            {/* Accordeons with question reviews */}
            <Card className="lg:col-span-8">
              <CardHeader>
                <CardTitle>Interview Transcript & Feedback</CardTitle>
                <CardDescription>Detailed review of your answers</CardDescription>
              </CardHeader>
              <CardContent className="pt-0">
                <Accordion>
                  {(activeSession.responses as any[]).map((item, idx) => (
                    <AccordionItem key={idx} title={`Q${idx + 1}: ${item.questionText}`}>
                      <div className="space-y-4">
                        {/* User Answer */}
                        <div className="space-y-1">
                          <h4 className="text-[10px] uppercase font-bold tracking-widest text-[#6B6A8A]">
                            Your Answer
                          </h4>
                          <p className="text-xs text-[#1A1832] leading-relaxed bg-[#F4F3FF]/40 p-3 rounded-xl border border-[#3C3489]/5 italic">
                            &ldquo;{item.answerText || 'No response provided.'}&rdquo;
                          </p>
                        </div>

                        {/* Grading Feedback */}
                        <div className="space-y-1.5 border-l-4 border-[#3C3489] pl-3 py-0.5 bg-[#3C3489]/5 p-3 rounded-r-xl">
                          <h4 className="text-[10px] uppercase font-black tracking-widest text-[#3C3489] flex items-center gap-1.5">
                            <Sparkles className="w-3.5 h-3.5 text-[#D85A30]" /> AI Feedback (Score: {item.score}%)
                          </h4>
                          <p className="text-xs text-[#6B6A8A] leading-relaxed">
                            {item.feedback}
                          </p>
                        </div>
                      </div>
                    </AccordionItem>
                  ))}
                </Accordion>
              </CardContent>
            </Card>
          </div>
        </div>
      )}
    </motion.div>
  );
}
